### PR TITLE
fix Ruby 3.1 ERB deprecation notices

### LINKED ISSUE #26: Ruby 3.1 ERB deprecation notices
On Ruby 3.1.x, `simplecov-rcov` triggers the following deprecation messages:

```
/home/dev/.rvm/gems/ruby-3.1.1/gems/simplecov-rcov-0.2.3/lib/simplecov-rcov.rb:57: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
/home/dev/.rvm/gems/ruby-3.1.1/gems/simplecov-rcov-0.2.3/lib/simplecov-rcov.rb:57: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
/home/dev/.rvm/gems/ruby-3.1.1/gems/simplecov-rcov-0.2.3/lib/simplecov-rcov.rb:57: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
/home/dev/.rvm/gems/ruby-3.1.1/gems/simplecov-rcov-0.2.3/lib/simplecov-rcov.rb:57: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
```

The warnings are triggered by: https://github.com/fguillen/simplecov-rcov/blob/4311cceb04b6767a2478cfc1582dbb61e07157bd/lib/simplecov-rcov.rb#L57 

Changing it to the following should stop the messages:

```ruby
ERB.new(File.read(File.join(File.dirname(__FILE__), '../views/', "#{name}.erb")), trim_mode: '-') 
```

The solution works on all maintained Ruby versions (currently 2.6, 2.7, 3.0 and 3.1).

### PR DESCRIPTION
**Pull request by joshRpowell**
@fguillen closes #26

### CODE REVIEW

**Comment by pboling** [comment]
ping @fguillen

**Comment by pboling** [comment]
🥇 Please!

**Comment by pboling** [comment]
@fguillen Would love to have my spec suite stop emitting soo much noice!  Please consider this PR!

**Comment by fguillen** [comment]
oki doki :)

**Comment by fguillen** [comment]
Version bumped to 0.3.3

**Pull request merged**
